os:
- linux
language: elixir
elixir:
- 1.0.5
otp_release:
- 17
notifications:
  email: false
script:
- echo "getting cibash scripts"
- wget https://github.com/timCF/cibash/archive/0.0.3.tar.gz
- tar xvzf ./0.0.3.tar.gz
- echo "START elixir build script"
- "./cibash-0.0.3/elixir_yandex.sh megaclicker megaclicker rel"
- echo "END elixir build script"
